### PR TITLE
Feature/new layout

### PR DESCRIPTION
**Pull request by harakoji**

### CODE REVIEW

**Comment by harakoji** [comment]
[https://gyazo.com/56300eaf5d178d979826529ccc1c5daa](https://gyazo.com/56300eaf5d178d979826529ccc1c5daa)

**Comment by chrhsmt** [comment]
[LGTM](http://lgtm.in/i/wQ6nHXcxn)

**Comment by atakei** [comment]
見ました :+1:

**Comment by KenyaOkada** [comment]
:+1:

**Pull request merged**
