### PR TITLE
Feature/new layout

### PR DESCRIPTION
**Pull request by harakoji**

### CODE REVIEW

**Comment by harakoji** [comment]
[https://gyazo.com/e21978ad72c5afc25b2f2b3bb6c3055d](https://gyazo.com/e21978ad72c5afc25b2f2b3bb6c3055d)

**Comment by harakoji** [comment]
[https://gyazo.com/23b32c52bf5870834eeaad84d7e7ba35](https://gyazo.com/23b32c52bf5870834eeaad84d7e7ba35)

**Comment by chrhsmt** [comment]
:+1:

**Comment by KenyaOkada** [comment]
:+1:

**Pull request merged**
